### ISSUE TITLE
Ubuntu 18.04.2 wine dependency issues

### ISSUE THREAD

**Issue by dundir** [liberodark/GW2-Wine#1]
Hi Armored,

I've been working through your posts in getting wine up and running on Ubuntu 18.04.2 x64 for gw2.  I've very little experience with wine; but it seems there are some missing dependencies or wine isn't finding the shared libraries.

The first debug log is found here:
https://pastebin.com/K0EY8sDB

Installing the following packages fixed most of the errs and the install was fairly simple:
libgnutls:i386 libfreetype6:i386 libgssapi-krb5-2:i386

The main problem is with ntlm_auth which is normally in the winbind package. The winbind package for i386 requires a whole slew of additional dependencies to install. 

winbind -> samba-libs:i386 -> python-talloc:i386 -> libbz2-1.0:i386 ->

libdb5.3:i386 libgpm2:i386 libncursesw5:i386 libpython2.7:i386
libpython2.7-minimal:i386 libpython2.7-stdlib:i386 libreadline7:i386 libsqlite3-0:i386
libssl1.1 libssl1.1:i386 libtalloc2:i386

...and it just keeps going deeper. Any suggestions?

Would it be possible to include the appropriate 32bit shared libraries.

Installing the 64 bit version's while removing the ntlm_auth error do freeze the patcher at initializing for me, even when its run in a virtual desktop.

https://pastebin.com/naWRdwkg

#> inxi -g
Graphics:  Card: Advanced Micro Devices [AMD/ATI] Baffin [Radeon RX 460/560D / Pro 450/455/460/555/560]
           Display Server: x11 (X.Org 1.19.6 ) driver: amdgpu Resolution: 1920x1080@60.00hz
           OpenGL: renderer: Radeon RX 560 Series (POLARIS11, DRM 3.27.0, 4.19.0-041900-generic, LLVM 8.0.0)
           version: 4.5 Mesa 19.1.0 - padoka PPA

Edit: It wasn't clear from my original post. I'm attempting to get the x64 version of the client running.

**Comment by liberodark** [comment]
need to see that but have possibility to implement lib32

**Comment by jrugia** [comment]
Hi, Armored here.

In order to resolve the dependency issue with 32bit, it's highly recommend to install the Wine package from Ubuntu's own repository as this will install all the required dependencies (inc 32bit ones).

I made a video which addresses most common issues with GW2 on Linux and goes through the entire process. Link here: https://www.youtube.com/watch?v=bmTztsi0OLU

The video is targeted mainly at Ubuntu and Debian based distros.

**Comment by dundir** [comment]
I've had a chance to look a bit more into this problem. A lot of the difficulty is being reduced now that multi-arch libraries are becoming more available but there are still some holdouts (libgstreamer) that might create problems (I haven't found a multilib for that library just yet). 

The lowest maintenance long term packaging solution seems to be converting the wine autotools build scripts to mesonbuild with appropriate mesonbuild subprojects for dependencies. Mesa3d has already completed their conversion so there are only a few smaller dependency packages that would need to converted.

I'm not that experienced with building from source so unfortunately I haven't yet been able to get a working build yet of a plain WoW64 wine build on Ubuntu 18.04.2 LTS. 

I've been debating writing a transcompiler for m4->bash->mesonbuild configs but that's a long way off and if I'm being realistic it probably won't happen. My knowledge of parsers and lexical analyzers is only a couple read throughs deep of the first few chapters of Aho/Ullman Dragon book.

There was little support from the RFC i submitted to the wine-devel mailing list regarding changing the build tooling to mesonbuild so even if that work was done there would likely be little chance of a pull request being accepted anytime soon.

**Comment by liberodark** [comment]
New version would be fix that
Into info.txt you see all information for play correctly.
Only need time for work on
